// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WKTechnology.Data;

#nullable disable

namespace WKTechnology.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220916025428_MigrationV6")]
    partial class MigrationV6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WKTechnology.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NameCategory");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("WKTechnology.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<int?>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ncm");

                    b.Property<decimal?>("PriceCost")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PriceCost");

                    b.Property<decimal?>("PriceSale")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PriceSale");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WKTechnology.Models.Products", b =>
                {
                    b.HasOne("WKTechnology.Models.Categories", "CategoriaNavigation")
                        .WithMany("Products")
                        .HasForeignKey("Categoria");

                    b.Navigation("CategoriaNavigation");
                });

            modelBuilder.Entity("WKTechnology.Models.Categories", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
