// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WKTechnology.Data;

#nullable disable

namespace WKTechnology.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220915215742_MigrationV2")]
    partial class MigrationV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WKTechnology.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Ncm")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ncm");

                    b.Property<decimal?>("PriceCost")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PriceCost");

                    b.Property<decimal?>("PriceSale")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PriceCost");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
